export default {
  APARTMENT_LIST_REQUEST: '@apartment/LIST_REQUEST',
  APARTMENT_LIST_SUCCESS: '@apartment/LIST_SUCCESS',
  APARTMENT_LIST_FAILURE: '@apartment/LIST_FAILURE',
  APARTMENT_SAVE_REQUEST: '@apartment/SAVE_REQUEST',
  APARTMENT_DELETE_REQUEST: '@apartment/DELETE_REQUEST',
};
