export default {
  DWELLER_LIST_REQUEST: '@dweller/LIST_REQUEST',
  DWELLER_LIST_SUCCESS: '@dweller/LIST_SUCCESS',
  DWELLER_LIST_FAILURE: '@dweller/LIST_FAILURE',
  DWELLER_SAVE_REQUEST: '@dweller/SAVE_REQUEST',
  DWELLER_DELETE_REQUEST: '@dweller/DELETE_REQUEST',
};
