export default {
  BLOCK_LIST_REQUEST: '@block/LIST_REQUEST',
  BLOCK_LIST_SUCCESS: '@block/LIST_SUCCESS',
  BLOCK_LIST_FAILURE: '@block/LIST_FAILURE',
  BLOCK_SAVE_REQUEST: '@block/SAVE_REQUEST',
  BLOCK_DELETE_REQUEST: '@block/DELETE_REQUEST',
};
